repos:
  - repo: local
    hooks:
      - id: pip-compile-multi-verify
        name: pip-compile-multi verify
        language: system
        entry: python -m pipcompilemulti.cli_v1 verify
        files: ^requirements/
        pass_filenames: false
        require_serial: true
        types: [file, non-executable, text]

      - id: ruff-check
        name: Ruff
        language: system
        entry: python -m ruff check --fix
        types_or: [python, pyi]
        require_serial: true

      - id: isort
        name: isort
        language: system
        entry: python -m isort
        types_or: [python, pyi]
        require_serial: true

      - id: black
        name: Black
        language: system
        entry: python -m black --config black.toml
        types_or: [python, pyi]
        require_serial: true

      - id: trailing-whitespace
        name: Trim trailing whitespace
        language: system
        entry: python -m pre_commit_hooks.trailing_whitespace_fixer
        types: [text]
