[tox]
envlist = py{310,311,312,313,314,315,py3}-{linux,windows,darwin}, lint, typing, checkdocs, verify
skip_missing_interpreters = true

[testenv]
platform = linux: linux
           windows: win32
           darwin: darwin
commands = python -m pytest --cov=pipcompilemulti --cov-branch --cov-report=html
deps =
    linux: -r{toxinidir}/requirements/test.hash
    darwin: -r{toxinidir}/requirements/test.hash
    windows: -r{toxinidir}/requirements/test.hash
    windows: -r{toxinidir}/requirements/testwin.hash

[testenv:lint]
skip_install = true
basepython = python3.10
commands =
    ruff check .
    isort --check-only .
    black --config black.toml --check .
    pylint -r y pipcompilemulti/ tests/
deps =
    -r{toxinidir}/requirements/local.hash

[testenv:typing]
skip_install = true
basepython = python3.10
commands =
    mypy pipcompilemulti
    pyright --pythonpath {envpython}
    ty check --python {envpython} pipcompilemulti
deps =
    -r{toxinidir}/requirements/local.hash

[testenv:checkdocs]
skip_install = true
basepython = python3.10
commands =
    python -m build --no-isolation --outdir {envtmpdir}/dist
    python -m twine check --strict {envtmpdir}/dist/*
deps =
    -r{toxinidir}/requirements/local.hash

[testenv:verify]
skipsdist = true
skip_install = true
basepython = python3.10
deps = pip-compile-multi
commands = pip-compile-multi verify
whitelist_externals = pip-compile-multi

[testenv:lock]
basepython = python3.10
usedevelop = True
deps = -rrequirements/test.hash
commands =
    requirements lock

[testenv:upgrade]
basepython = python3.10
usedevelop = True
deps = -rrequirements/test.hash
commands =
    requirements upgrade

[pytest]
addopts = -vvvs --doctest-modules
log_cli = true
log_level = NOTSET
