"""
Global dictionary holding configuration options
"""

OPTIONS = {
    'header_file': None,
    'include_names': [],
}

DEFAULT_HEADER = """
#
# This file is autogenerated by pip-compile-multi
# To update, run:
#
#    pip-compile-multi
#
""".lstrip()
